//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/stackitcloud/gardener-extension-runtime-kata/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KataConfiguration)(nil), (*config.KataConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KataConfiguration_To_config_KataConfiguration(a.(*KataConfiguration), b.(*config.KataConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.KataConfiguration)(nil), (*KataConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KataConfiguration_To_v1alpha1_KataConfiguration(a.(*config.KataConfiguration), b.(*KataConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_KataConfiguration_To_config_KataConfiguration(in *KataConfiguration, out *config.KataConfiguration, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_KataConfiguration_To_config_KataConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_KataConfiguration_To_config_KataConfiguration(in *KataConfiguration, out *config.KataConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KataConfiguration_To_config_KataConfiguration(in, out, s)
}

func autoConvert_config_KataConfiguration_To_v1alpha1_KataConfiguration(in *config.KataConfiguration, out *KataConfiguration, s conversion.Scope) error {
	return nil
}

// Convert_config_KataConfiguration_To_v1alpha1_KataConfiguration is an autogenerated conversion function.
func Convert_config_KataConfiguration_To_v1alpha1_KataConfiguration(in *config.KataConfiguration, out *KataConfiguration, s conversion.Scope) error {
	return autoConvert_config_KataConfiguration_To_v1alpha1_KataConfiguration(in, out, s)
}
