apiVersion: v1
description: A Helm chart to deploy the admission-runtime-kata-virtual-garden application related resources
name: admission-runtime-kata-virtual-garden
version: 0.1.0
sources:
  - https://github.com/stackitcloud/gardener-extension-runtime-kata
